### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tumainimosha** [dbrax/tra-api-laravel#1]
Hi @dbrax was interested in the title of this project, and thought to open this issue to know more about the roadmap of this project. For instance which TRA APIs are you looking at including in this wrapper... thanks

**Comment by dbrax** [comment]
Hello @tumainimosha 

Thanks for taking interest on this particular opensource project.

TRA has released an api to their system ( VFD ) sort of virtual edf. Using it on some internal projects hence was looking to create a wrapper for their api available for the public.

I wont close this issue at the moment. I will explain more on the roadmap etc on coming two weeks.

Hope we can join our expertise to contribute and develop a good lib.

**Comment by tumainimosha** [comment]
Hi @dbrax thanks for the feedback. This is good initiative, looking forward to chip in where I could.

Here is a link to a similar repo I found for node https://github.com/husseinmkwizu/node-tra by @husseinmkwizu
